import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { API_BASE, apiRequest, type SwAccount, type SwDevice } from "./api";
import { rememberSwAccount } from "./rememberedAccounts";
import { SW_IDENTITY_VERSION } from "./security";

type View = "profile" | "security" | "devices" | "subscriptions" | "connections";
type TotpSetup = { setupId: string; secret: string; formattedSecret: string; otpauthUri: string; expiresAt: string };
type QrMethod = "qr" | "key";
type ConfirmAction = { kind: "logout" } | { kind: "device"; device: SwDevice } | null;
type SecurityMethod = "email" | "totp" | null;

declare const qrcode: ((typeNumber: number, errorCorrectionLevel: "H") => { addData(data: string): void; make(): void; createDataURL(cellSize: number, margin: number): string }) | undefined;

const avatarPresets = ["orbit-cyan", "signal-acid", "core-cobalt", "flare-coral", "node-violet", "identity-paper"] as const;
const viewOrder: View[] = ["profile", "security", "devices", "subscriptions", "connections"];

function avatarLabel(value: string) {
  return ({ "orbit-cyan": "Yörünge", "signal-acid": "Sinyal", "core-cobalt": "Çekirdek", "flare-coral": "Parlama", "node-violet": "Düğüm", "identity-paper": "Kimlik" } as Record<string, string>)[value] || "SW";
}

function deviceTitle(userAgent: string) {
  const browser = /Edg\//.test(userAgent) ? "Microsoft Edge" : /Firefox\//.test(userAgent) ? "Mozilla Firefox" : /Chrome\//.test(userAgent) ? "Google Chrome" : /Safari\//.test(userAgent) ? "Safari" : "Web tarayıcısı";
  const system = /Windows/.test(userAgent) ? "Windows" : /Android/.test(userAgent) ? "Android" : /iPhone|iPad/.test(userAgent) ? "iOS" : /Mac OS/.test(userAgent) ? "macOS" : /Linux/.test(userAgent) ? "Linux" : "Bilinmeyen sistem";
  return `${browser} · ${system}`;
}

function dateTime(value: number) {
  return new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short" }).format(value * 1000);
}

function mapUrls(device: SwDevice) {
  const { latitude, longitude, city, region, country } = device.location;
  if (latitude !== null && longitude !== null) {
    const delta = .08;
    return { embed: `https://www.openstreetmap.org/export/embed.html?bbox=${longitude - delta}%2C${latitude - delta}%2C${longitude + delta}%2C${latitude + delta}&layer=mapnik&marker=${latitude}%2C${longitude}`, external: `https://www.openstreetmap.org/?mlat=${latitude}&mlon=${longitude}#map=10/${latitude}/${longitude}` };
  }
  return { embed: "", external: `https://www.openstreetmap.org/search?query=${encodeURIComponent([city, region, country].filter(Boolean).join(", "))}` };
}

function SecurityCode({ method, value, onChange }: { method: SecurityMethod; value: string; onChange: (value: string) => void }) {
  if (!method) return null;
  return <label>{method === "totp" ? "Authenticator veya kurtarma kodu" : "E-postaya gelen 6 haneli kod"}<input value={value} onChange={(event) => onChange(event.target.value)} autoComplete="one-time-code" inputMode={method === "email" ? "numeric" : "text"} placeholder={method === "email" ? "123456" : "123456 veya XXXX-XXXX"} required /></label>;
}

function PasswordInput({ label, value, onChange, visible, toggle, autoComplete = "current-password" }: { label: string; value: string; onChange: (value: string) => void; visible: boolean; toggle: () => void; autoComplete?: string }) {
  return <label>{label}<span className="secure-input"><input type={visible ? "text" : "password"} value={value} onChange={(event) => onChange(event.target.value)} autoComplete={autoComplete} minLength={autoComplete === "new-password" ? 10 : undefined} required /><button type="button" onClick={toggle} aria-label={visible ? "Şifreyi gizle" : "Şifreyi göster"}><span className="password-signal-visor" aria-hidden="true"><i /><b /><em /></span></button></span></label>;
}

export function MemberPage() {
  const [account, setAccount] = useState<SwAccount | null>(null);
  const [view, setView] = useState<View>(() => { const requested = new URLSearchParams(window.location.search).get("view"); return viewOrder.includes(requested as View) ? requested as View : "profile"; });
  const [username, setUsername] = useState("");
  const [avatarPreset, setAvatarPreset] = useState("orbit-cyan");
  const [avatarRevision, setAvatarRevision] = useState(0);
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState("");
  const [totpSetup, setTotpSetup] = useState<TotpSetup | null>(null);
  const [totpCode, setTotpCode] = useState("");
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const [recoveryCodeCheck, setRecoveryCodeCheck] = useState("");
  const [qrMethod, setQrMethod] = useState<QrMethod>("qr");
  const [showPasswords, setShowPasswords] = useState(false);
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [newPasswordRepeat, setNewPasswordRepeat] = useState("");
  const [passwordCode, setPasswordCode] = useState("");
  const [passwordMethod, setPasswordMethod] = useState<SecurityMethod>(null);
  const [newEmail, setNewEmail] = useState("");
  const [emailPassword, setEmailPassword] = useState("");
  const [emailCode, setEmailCode] = useState("");
  const [emailMethod, setEmailMethod] = useState<SecurityMethod>(null);
  const [deletePassword, setDeletePassword] = useState("");
  const [deleteCode, setDeleteCode] = useState("");
  const [deleteMethod, setDeleteMethod] = useState<SecurityMethod>(null);
  const [devices, setDevices] = useState<SwDevice[]>([]);
  const [deviceCountdown, setDeviceCountdown] = useState(5);
  const [visibleLocation, setVisibleLocation] = useState<string | null>(null);
  const [confirmAction, setConfirmAction] = useState<ConfirmAction>(null);
  const [connectionNotice] = useState(() => { const params = new URLSearchParams(window.location.search); return params.get("linked") ? `${params.get("linked") === "google" ? "Google" : "Kick"} hesabın SW Identity ağına bağlandı.` : params.get("link_error") ? "Bağlantı kurulamadı veya bu sağlayıcı başka bir hesaba bağlı." : ""; });
  const [connectionConfirm, setConnectionConfirm] = useState<"google" | "kick" | "play-streamers" | null>(null);

  const totpQrDataUrl = useMemo(() => { if (!totpSetup || typeof qrcode !== "function") return ""; try { const qr = qrcode(0, "H"); qr.addData(totpSetup.otpauthUri); qr.make(); return qr.createDataURL(6, 4); } catch { return ""; } }, [totpSetup]);
  const loadAccount = async () => { const data = await apiRequest<SwAccount>("/api/account"); rememberSwAccount(data); setAccount(data); setUsername(data.user.username || data.user.displayName); setNewEmail(data.user.email || ""); setAvatarPreset(data.user.avatar.type === "preset" ? data.user.avatar.value : "orbit-cyan"); return data; };
  const loadDevices = async () => { const data = await apiRequest<{ devices: SwDevice[] }>("/api/account/devices"); setDevices(data.devices); setDeviceCountdown(5); };

  useEffect(() => { loadAccount().catch(() => window.location.replace("/account/")); }, []);
  useEffect(() => { const nextUrl = new URL(window.location.href); nextUrl.searchParams.set("view", view); window.history.replaceState({}, "", nextUrl); setStatus(""); if (view !== "devices") return; void loadDevices(); const timer = window.setInterval(() => setDeviceCountdown((value) => value <= 1 ? 5 : value - 1), 1000); const poller = window.setInterval(() => { if (!document.hidden) void loadDevices(); }, 5000); return () => { window.clearInterval(timer); window.clearInterval(poller); }; }, [view]);

  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setStatus(""); try { const data = await apiRequest<SwAccount>("/api/account/profile", { method: "PUT", body: JSON.stringify({ username, avatarPreset }) }); setAccount(data); rememberSwAccount(data); setStatus("Profil bilgilerin kaydedildi."); } catch (error) { setStatus(error instanceof Error ? error.message : "Profil kaydedilemedi."); } finally { setBusy(false); } }
  async function uploadAvatar(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setBusy(true); setStatus(""); try { const form = new FormData(); form.set("file", file); const data = await apiRequest<SwAccount>("/api/account/avatar", { method: "POST", body: form }); setAccount(data); rememberSwAccount(data); setAvatarRevision(Date.now()); setStatus("Profil fotoğrafın kaydedildi."); } catch (error) { setStatus(error instanceof Error ? error.message : "Profil fotoğrafı yüklenemedi."); } finally { setBusy(false); event.target.value = ""; } }

  async function challenge(action: "email_change" | "password_change" | "account_delete", current: string, extra: Record<string, string> = {}) { const data = await apiRequest<{ method: "email" | "totp"; email?: string }>("/api/account/security/challenge", { method: "POST", body: JSON.stringify({ action, currentPassword: current, ...extra }) }); setStatus(data.method === "totp" ? "Authenticator uygulamandaki kodu gir." : `Doğrulama kodu ${data.email || "e-posta adresine"} gönderildi.`); return data.method; }
  async function changeEmail(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setStatus(""); try { if (!emailMethod) { setEmailMethod(await challenge("email_change", emailPassword, { newEmail })); return; } const data = await apiRequest<SwAccount>("/api/account/email", { method: "POST", body: JSON.stringify({ newEmail, currentPassword: emailPassword, code: emailCode }) }); setAccount(data); rememberSwAccount(data); setEmailPassword(""); setEmailCode(""); setEmailMethod(null); setStatus("E-posta adresin değiştirildi; diğer cihazlardaki oturumlar kapatıldı."); } catch (error) { setStatus(error instanceof Error ? error.message : "E-posta değiştirilemedi."); } finally { setBusy(false); } }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setStatus(""); try { if (!passwordMethod) { setPasswordMethod(await challenge("password_change", currentPassword)); return; } await apiRequest("/api/account/password", { method: "POST", body: JSON.stringify({ currentPassword, newPassword, newPasswordRepeat, code: passwordCode }) }); setCurrentPassword(""); setNewPassword(""); setNewPasswordRepeat(""); setPasswordCode(""); setPasswordMethod(null); setStatus("Şifren değiştirildi ve diğer cihazlardaki oturumlar kapatıldı."); } catch (error) { setStatus(error instanceof Error ? error.message : "Şifre değiştirilemedi."); } finally { setBusy(false); } }
  async function removeAccount(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setStatus(""); try { if (!deleteMethod) { setDeleteMethod(await challenge("account_delete", deletePassword)); return; } await apiRequest("/api/account/delete", { method: "POST", body: JSON.stringify({ currentPassword: deletePassword, code: deleteCode }) }); window.location.replace("/"); } catch (error) { setStatus(error instanceof Error ? error.message : "Hesap silinemedi."); } finally { setBusy(false); } }

  async function startTwoFactor() { setBusy(true); setStatus(""); setRecoveryCodes([]); try { setQrMethod("qr"); setTotpSetup(await apiRequest<TotpSetup>("/api/account/totp/setup", { method: "POST", body: "{}" })); } catch (error) { setStatus(error instanceof Error ? error.message : "Kurulum başlatılamadı."); } finally { setBusy(false); } }
  async function confirmTwoFactor(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!totpSetup) return; setBusy(true); setStatus(""); try { const data = await apiRequest<SwAccount & { recoveryCodes: string[] }>("/api/account/totp/confirm", { method: "POST", body: JSON.stringify({ setupId: totpSetup.setupId, code: totpCode }) }); setAccount(data); setRecoveryCodes(data.recoveryCodes); setTotpSetup(null); setTotpCode(""); setStatus("Doğrulama uygulaması bağlandı. Kurtarma kodlarını güvenli bir yere kaydet."); } catch (error) { setStatus(error instanceof Error ? error.message : "Kod doğrulanamadı."); } finally { setBusy(false); } }
  async function regenerateRecovery(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setStatus(""); try { const data = await apiRequest<{ recoveryCodes: string[] }>("/api/account/totp/recovery/regenerate", { method: "POST", body: JSON.stringify({ code: recoveryCodeCheck }) }); setRecoveryCodes(data.recoveryCodes); setRecoveryCodeCheck(""); setStatus("Yeni kurtarma kodların oluşturuldu. Önceki kodların tamamı devre dışı bırakıldı."); } catch (error) { setStatus(error instanceof Error ? error.message : "Kurtarma kodları yenilenemedi."); } finally { setBusy(false); } }
  async function disableTwoFactor(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setStatus(""); try { const data = await apiRequest<SwAccount>("/api/account/totp/disable", { method: "POST", body: JSON.stringify({ code: totpCode }) }); setAccount(data); setTotpCode(""); setRecoveryCodes([]); setStatus("Doğrulama uygulaması bağlantısı kaldırıldı."); } catch (error) { setStatus(error instanceof Error ? error.message : "Doğrulama kapatılamadı."); } finally { setBusy(false); } }
  async function logout() { setBusy(true); await apiRequest("/api/auth/logout", { method: "POST", body: "{}" }).catch(() => undefined); window.location.replace("/"); }
  async function revokeDevice(device: SwDevice) { setBusy(true); try { const data = await apiRequest<{ ok: boolean; current: boolean }>(`/api/account/devices/${device.id}`, { method: "DELETE" }); if (data.current) window.location.replace("/account/"); else { setConfirmAction(null); await loadDevices(); } } catch (error) { setStatus(error instanceof Error ? error.message : "Oturum kapatılamadı."); setConfirmAction(null); } finally { setBusy(false); } }
  async function disconnectConnection() { if (!connectionConfirm) return; const provider = connectionConfirm; setBusy(true); setStatus(""); try { const data = await apiRequest<{ account: SwAccount }>(`/api/account/connections/${provider}`, { method: "DELETE" }); setAccount(data.account); setConnectionConfirm(null); setStatus(`${provider === "play-streamers" ? "Play Streamers" : provider === "google" ? "Google" : "Kick"} bağlantısı kesildi.`); } catch (error) { setStatus(error instanceof Error ? error.message : "Bağlantı kesilemedi."); setConnectionConfirm(null); } finally { setBusy(false); } }

  if (!account) return <main className="member-shell"><div className="member-loading">SW MERKEZİ HAZIRLANIYOR…</div></main>;
  const avatarUrl = account.user.avatar.type === "custom" ? `${API_BASE}${account.user.avatar.url}?v=${avatarRevision}` : null;
  const viewNames: Record<View, string> = { profile: "Profil", security: "Güvenlik", devices: "Cihazlar", subscriptions: "Abonelikler", connections: "Bağlı platformlar" };

  return <main className="member-shell account-center-shell">
    <header className="member-topbar"><a href="/home/" className="member-brand"><img src="/brand/swcreate-logo.png" alt="" /><span>SW CREATE<small>HESAP MERKEZİ</small></span></a><div className="member-top-status"><i /> SW AĞI BAĞLI</div><button onClick={() => setConfirmAction({ kind: "logout" })} disabled={busy}>Çıkış yap</button></header>
    <div className="member-layout"><aside><p>SW IDENTITY</p>{viewOrder.map((item, index) => <button key={item} className={view === item ? "active" : ""} disabled={view === item} onClick={() => setView(item)}><span>{String(index + 1).padStart(2, "0")}</span>{viewNames[item]}</button>)}</aside>
      <section className="member-content account-center-content">
        {view === "profile" && <div className="account-view"><div className="account-view-heading"><p>SW HESABI · PROFİL</p><h1>Profilini düzenle</h1><span>Kullanıcı adını ve profil fotoğrafını buradan yönet.</span></div><div className="account-profile-identity"><div className={`account-avatar ${account.user.avatar.type === "preset" ? account.user.avatar.value : "custom"}`}>{avatarUrl ? <img src={avatarUrl} alt="Profil fotoğrafı" /> : <img src="/brand/swcreate-logo.png" alt="" />}</div><div><strong>{account.user.username}</strong><span>{account.user.email || "SW Identity hesabı"}</span></div></div><form className="account-settings-card" onSubmit={saveProfile}><h2>Kullanıcı adı</h2><p>Yeni kullanıcı adın 3–32 karakter olmalıdır.</p><label>Kullanıcı adı<input value={username} onChange={(event) => setUsername(event.target.value)} minLength={3} maxLength={32} pattern="[A-Za-z0-9._-]+" required /></label><button disabled={busy}>Kullanıcı adını kaydet</button></form><section className="account-settings-card"><h2>Profil fotoğrafı</h2><p>Hazır bir SW kimliği seçebilir veya bu cihazdan kendi fotoğrafını kullanabilirsin.</p><div className="avatar-preset-list">{avatarPresets.map((preset) => <button type="button" key={preset} className={account.user.avatar.type === "preset" && avatarPreset === preset ? `active ${preset}` : preset} onClick={() => setAvatarPreset(preset)} title={avatarLabel(preset)}><img src="/brand/swcreate-logo.png" alt="" /></button>)}</div><label className="avatar-upload-button">Kendi fotoğrafını seç<input type="file" accept="image/png,image/jpeg,image/webp" onChange={uploadAvatar} disabled={busy} /></label><button type="button" className="avatar-save-preset" onClick={() => void saveProfile({ preventDefault() {} } as FormEvent<HTMLFormElement>)} disabled={busy}>Seçili SW görselini kaydet</button></section>{status && <p className="account-view-status">{status}</p>}</div>}

        {view === "security" && <div className="account-view"><div className="account-view-heading"><p>SW IDENTITY v{SW_IDENTITY_VERSION}</p><h1>E-posta, şifre ve güvenlik</h1><span>Önemli işlemler, açıksa Authenticator; değilse e-posta koduyla doğrulanır.</span></div>
          <form className="account-settings-card" onSubmit={changeEmail}><h2>E-posta</h2><p>Yeni adresini mevcut şifren ve SW Identity doğrulamasıyla değiştirebilirsin.</p><label>Yeni e-posta<input type="email" value={newEmail} onChange={(event) => { setNewEmail(event.target.value); setEmailMethod(null); }} required /></label><PasswordInput label="Mevcut şifre" value={emailPassword} onChange={(value) => { setEmailPassword(value); setEmailMethod(null); }} visible={showPasswords} toggle={() => setShowPasswords((shown) => !shown)} /><SecurityCode method={emailMethod} value={emailCode} onChange={setEmailCode} /><button disabled={busy}>{emailMethod ? "E-postayı değiştir" : "Güvenlik doğrulamasını başlat"}</button></form>
          <form className="account-settings-card" onSubmit={changePassword}><h2>Şifre</h2><p>Şifren değiştirildiğinde bu cihaz dışındaki açık oturumlar kapatılır.</p><PasswordInput label="Mevcut şifre" value={currentPassword} onChange={(value) => { setCurrentPassword(value); setPasswordMethod(null); }} visible={showPasswords} toggle={() => setShowPasswords((shown) => !shown)} /><PasswordInput label="Yeni şifre" value={newPassword} onChange={setNewPassword} visible={showPasswords} toggle={() => setShowPasswords((shown) => !shown)} autoComplete="new-password" /><PasswordInput label="Yeni şifre tekrar" value={newPasswordRepeat} onChange={setNewPasswordRepeat} visible={showPasswords} toggle={() => setShowPasswords((shown) => !shown)} autoComplete="new-password" /><SecurityCode method={passwordMethod} value={passwordCode} onChange={setPasswordCode} /><button disabled={busy}>{passwordMethod ? "Şifreyi değiştir" : "Güvenlik doğrulamasını başlat"}</button><a className="account-card-link" href="/account/?forgot=1">Şifremi unuttum</a></form>
          <section className="account-settings-card"><h2>Doğrulama uygulaması</h2><p>{account.security.twoFactorEnabled ? "Açık. Yeni girişler ve önemli hesap işlemleri Authenticator koduyla korunuyor." : "Kapalı. Google Authenticator, Microsoft Authenticator ve standart TOTP uygulamalarıyla çalışır."}</p>{!account.security.twoFactorEnabled && !totpSetup && <button onClick={startTwoFactor} disabled={busy}>Doğrulama uygulaması bağla</button>}{totpSetup && <section className="totp-setup"><span>1. Authenticator uygulamana SW hesabını ekle</span><div className="totp-methods" role="tablist" aria-label="Authenticator kurulum yöntemi"><button type="button" role="tab" aria-selected={qrMethod === "qr"} className={qrMethod === "qr" ? "active" : ""} onClick={() => setQrMethod("qr")}>QR kodu tara</button><button type="button" role="tab" aria-selected={qrMethod === "key"} className={qrMethod === "key" ? "active" : ""} onClick={() => setQrMethod("key")}>Kurulum anahtarı</button></div>{qrMethod === "qr" && <div className="totp-qr-panel">{totpQrDataUrl ? <div className="totp-qr-code"><img src={totpQrDataUrl} alt="SW Create Authenticator QR kodu" /><span aria-hidden="true"><img src="/brand/swcreate-logo.png" alt="" /></span></div> : <p>QR sistemi yüklenemedi. Kurulum anahtarını kullanabilirsin.</p>}<strong>Authenticator uygulamanda “QR kodu tara” seçeneğini aç.</strong><small>QR yalnızca bu tarayıcıda oluşturulur.</small></div>}{qrMethod === "key" && <div className="totp-key-panel"><p>Kurulum anahtarını elle gir.</p><code>{totpSetup.formattedSecret}</code><a href={totpSetup.otpauthUri}>Authenticator uygulamasında aç</a></div>}<span>2. Uygulamanın ürettiği 6 haneli kodu doğrula</span><form onSubmit={confirmTwoFactor}><input value={totpCode} onChange={(event) => setTotpCode(event.target.value)} inputMode="numeric" autoComplete="one-time-code" minLength={6} maxLength={6} placeholder="123456" required /><button disabled={busy}>Doğrula ve aç</button></form></section>}{account.security.twoFactorEnabled && <form className="totp-disable" onSubmit={disableTwoFactor}><label>Bağlantıyı kaldırmak için kod<input value={totpCode} onChange={(event) => setTotpCode(event.target.value)} autoComplete="one-time-code" placeholder="123456 veya XXXX-XXXX" required /></label><button disabled={busy}>Doğrulama uygulamasını kaldır</button></form>}</section>
          {account.security.twoFactorEnabled && <section className="account-settings-card"><h2>Kurtarma kodları</h2><p>Yeni kodlar oluşturulduğunda önceki kurtarma kodlarının tamamı anında devre dışı kalır.</p><form className="totp-regenerate" onSubmit={regenerateRecovery}><label>Authenticator veya mevcut kurtarma kodu<input value={recoveryCodeCheck} onChange={(event) => setRecoveryCodeCheck(event.target.value)} autoComplete="one-time-code" placeholder="123456 veya XXXX-XXXX" required /></label><button disabled={busy}>Kurtarma kodlarını yenile</button></form></section>}
          {recoveryCodes.length > 0 && <section className="totp-recovery"><strong>Yeni kurtarma kodların</strong><p>Her kod yalnızca bir kez kullanılabilir. Bu ekran kapandıktan sonra kodlar yeniden gösterilmez.</p><div>{recoveryCodes.map((code) => <code key={code}>{code}</code>)}</div></section>}
          <form className="account-settings-card account-danger-card" onSubmit={removeAccount}><h2>Hesabı sil</h2><p>Profilin, oturumların, bağlı platformların ve destek verilerin kalıcı olarak silinir.</p><PasswordInput label="Mevcut şifre" value={deletePassword} onChange={(value) => { setDeletePassword(value); setDeleteMethod(null); }} visible={showPasswords} toggle={() => setShowPasswords((shown) => !shown)} /><SecurityCode method={deleteMethod} value={deleteCode} onChange={setDeleteCode} /><button disabled={busy}>{deleteMethod ? "Hesabı kalıcı olarak sil" : "Silme doğrulamasını başlat"}</button></form>{status && <p className="account-view-status">{status}</p>}</div>}

        {view === "devices" && <div className="account-view"><div className="account-view-heading"><p>SW OTURUM AĞI</p><h1>Oturum açılan cihazlar</h1><span>Hesabına giriş yapılan cihazları, açık oturumları, son etkinliği ve Cloudflare’ın yaklaşık konumunu kontrol et.</span></div><div className="device-refresh"><span>Son yenileme: şimdi · Açıkken {deviceCountdown} saniyede bir kontrol edilir.</span><button onClick={() => void loadDevices()}>↻ Yenile</button></div><div className="device-list">{devices.map((device) => { const location = [device.location.city, device.location.region, device.location.country].filter(Boolean).join(", ") || "Yaklaşık konum bilinmiyor"; const maps = mapUrls(device); return <article key={device.id}><div className="device-icon"><i /></div><div className="device-info"><strong>{deviceTitle(device.userAgent)} {device.current && <b>OTURUM AÇIK</b>}</strong><span>İlk giriş: {dateTime(device.createdAt)}</span><span>Son aktiflik: {dateTime(device.lastSeenAt)}</span></div><div className="device-actions"><button onClick={() => setVisibleLocation((current) => current === device.id ? null : device.id)}>{visibleLocation === device.id ? "Haritayı kapat" : "Konumu göster"}</button><button className="danger" onClick={() => setConfirmAction({ kind: "device", device })}>{device.current ? "Bu cihazdan çık" : "Oturumu kapat"}</button></div>{visibleLocation === device.id && <section className="device-map"><header><span>{location}</span><a href={maps.external} target="_blank" rel="noreferrer">Büyük haritada aç ↗</a></header>{maps.embed ? <iframe title={`${deviceTitle(device.userAgent)} yaklaşık konumu`} src={maps.embed} loading="lazy" referrerPolicy="no-referrer" /> : <p>Bu eski oturumda koordinat kaydı yok. Yaklaşık yer adını büyük haritada açabilirsin.</p>}</section>}</article>; })}</div>{status && <p className="account-view-status">{status}</p>}</div>}

        {view === "subscriptions" && <div className="account-view"><div className="account-view-heading"><p>SW ÜRÜN AĞI</p><h1>Abonelikler ve planlar</h1><span>Hangi üründe hangi plana sahip olduğunu ve erişim durumunu burada gör.</span></div><section className="subscription-summary"><span>MEVCUT ANA PLAN</span><strong>{account.subscriptions.find((item) => item.productId === "sw-create")?.planName || "SW Create Free Edition"}</strong><p>Merkezi kimlik, güvenlik, destek ve temel ürün erişimi etkin.</p><a href="/plans/">Tüm planları aç →</a></section><div className="subscription-list">{account.subscriptions.map((item) => <article key={item.productId}><div><i /><span><strong>{item.product}</strong><small>{item.planName}</small></span></div><b>{item.status === "active" ? "ETKİN" : item.status.toUpperCase()}</b></article>)}</div></div>}

        {view === "connections" && <div className="account-view"><div className="account-view-heading"><p>SW KİMLİK AĞI</p><h1>Bağlı platformlar</h1><span>SW ürünlerini ve hesabına giriş sağlayan platformları tek merkezden gör.</span></div>{connectionNotice && <p className="account-view-status">{connectionNotice}</p>}{status && <p className="account-view-status">{status}</p>}<div className="connection-groups"><section><span>SW ÜRÜNLERİ</span>{account.connections.filter((item) => item.provider === "sw-create" || item.provider === "play-streamers").map((item) => <article key={item.provider}><i className={item.provider}><img src={item.provider === "play-streamers" ? "/brand/play-streamers-ps-logo.svg" : "/brand/swcreate-logo.png"} alt="" /></i><div><strong>{item.label}</strong><small>{item.detail}</small></div>{item.provider === "play-streamers" && item.connected ? <div className="connection-connected-actions"><b>BAĞLI</b><button type="button" onClick={() => setConnectionConfirm("play-streamers")}>Bağlantıyı kes</button></div> : <b className={item.connected ? "connected" : "idle"}>{item.provider === "play-streamers" ? "YAKINDA" : item.connected ? "BAĞLI" : "HAZIR"}</b>}</article>)}</section><section><span>GİRİŞ SAĞLAYICILARI</span>{account.connections.filter((item) => item.provider === "google" || item.provider === "kick").map((item) => <article key={item.provider}><i className={item.provider}><img src={item.provider === "kick" ? "/brand/kick-k.svg" : "/brand/google-g.svg"} alt="" /></i><div><strong>{item.label}</strong><small>{item.detail}</small></div>{item.connected ? <div className="connection-connected-actions"><b>BAĞLI</b><button type="button" onClick={() => setConnectionConfirm(item.provider === "google" ? "google" : "kick")}>Bağlantıyı kes</button></div> : <a className="connection-link" href={`${API_BASE}/api/account/connections/${item.provider}/start`}>BAĞLA</a>}</article>)}</section></div></div>}
      </section></div>
    {confirmAction && <div className="member-confirm-overlay" role="dialog" aria-modal="true"><section><span>SW IDENTITY ONAYI</span><h2>{confirmAction.kind === "logout" ? "Hesabından çıkış yapılsın mı?" : "Bu oturum kapatılsın mı?"}</h2><p>{confirmAction.kind === "logout" ? "Bu cihazdaki SW oturumun güvenli şekilde kapatılacak." : `${deviceTitle(confirmAction.device.userAgent)} oturumu artık hesabına erişemeyecek.`}</p><div><button onClick={() => setConfirmAction(null)}>Vazgeç</button><button className="danger" disabled={busy} onClick={() => confirmAction.kind === "logout" ? void logout() : void revokeDevice(confirmAction.device)}>{busy ? "İŞLENİYOR…" : "ONAYLA"}</button></div></section></div>}
    {connectionConfirm && <div className="member-confirm-overlay" role="dialog" aria-modal="true"><section><span>SW IDENTITY BAĞLANTI ONAYI</span><h2>{connectionConfirm === "play-streamers" ? "Play Streamers" : connectionConfirm === "google" ? "Google" : "Kick"} bağlantısı kesilsin mi?</h2><p>Bu sağlayıcı artık SW hesabında giriş veya ürün bağlantısı olarak görünmeyecek. Hesabını kilitleyecek bir işlem güvenlik katmanı tarafından engellenir.</p><div><button onClick={() => setConnectionConfirm(null)}>Vazgeç</button><button className="danger" disabled={busy} onClick={() => void disconnectConnection()}>{busy ? "İŞLENİYOR…" : "BAĞLANTIYI KES"}</button></div></section></div>}
  </main>;
}
